### PR TITLE
Fix parsing of the service file

### PR DESCRIPTION
**Pull request by darix**
please also tag and release this.

### CODE REVIEW

**Comment by M0ses** [comment]
LGTM

**Comment by jfkw** [comment]
Thanks for the heads up and the commit.

- The missing end tag `</parameter>` will definitely go in.
- I would prefer change the description text to omit the problematic characters `[` and `]`  so we don't have to use syntactically correct CDATA sections going forward. I'll strip the embedded newlines in case those are also a problem for the parser.
- I wasn't aware of the parse problem. Beyond XML well-formedness e.g. missing end tag `</parameter>`, what tool and library is used that failed to parse? I can manually test now and possibly add a unit test in the future.

I'll push that commit, once I  figure out this PR's unusual source branch identity so I can push to it:

`wants to merge 1 commit into [openSUSE:master](https://github.com/openSUSE/obs-service-go_modules) from [openSUSE:master](https://github.com/openSUSE/obs-service-go_modules-1)` Is the `-1` something GitHub creates for web UI edited files? Normally there is a distinct fork I can add as a remote to push commits.

Since my change will be in conflict with the original commit from the PR, I will either force-push the one new commit or squash merge depending on what works with the PR system.

**Comment by darix** [comment]
i might have accidently branched into the openSUSE namespace. nothing to worry about.

**Comment by jfkw** [comment]
@darix can you [enable "Maintainers are allowed to edit this pull request."](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).

**Comment by darix** [comment]
if you can tell me where. i thought it was default.

**Comment by jfkw** [comment]
I expected maintainer editing to be on by default as well, but some PRs have it others do not.  No action needed.

**Comment by jfkw** [comment]
Closed in 3b2ddb0db8227fe75eab43e18fe7aa7ef6c2a6a6

**Comment by M0ses** [comment]
>     * I would prefer change the description text to omit the problematic characters `[` and `]`  

IMHO the parser fails because of `<` and `>`

> 
>     * I wasn't aware of the parse problem. Beyond XML well-formedness e.g. missing end tag `</parameter>`, what tool and library is used that failed to parse? I can manually test now and possibly add a unit test in the future.

In the obs backend the xml is parsed by `XML::Parser` used by `XML::Structured`.

I'm preparing a "short" guideline how to develop services and make them "production ready" in build.opensuse.org
There you can also find info how to check your `<service_name>.service`. ATM I created the following gh repo:

https://github.com/M0ses/obs-service-example

The namespace may change to "openSUSE" in near future! But you should already find all required information how to test your XML.

**Comment by jfkw** [comment]
@darix before we leave this topic, what tool and operation raises the service file XML parse error? I use the service in `disabledrun` mode frequently and never noticed.

**Comment by darix** [comment]
can you quickly tag a release and push the package out? thank you in advance :)

**Comment by jfkw** [comment]
Yes, v0.6.1 is tagged and submitted to Factory.

**Comment by M0ses** [comment]
JFTR - However it worked we now have https://github.com/openSUSE/obs-service-example

**Pull request closed without merging**
